/**
 * SR12 PARTNER STORE - MASTER DATA & DATABASE (V3 DISTINCT VISUALS)
 * Ekosistem Resmi Kemitraan SR12 Herbal Skin Care
 */

const SR12_TIERS = {
  konsumen: {
    id: 'konsumen',
    name: 'Konsumen Retail',
    label: 'Konsumen Umum',
    discountPct: 0,
    minOrderNominal: 0,
    minOrderPcs: 1,
    badgeColor: '#64748b',
    description: 'Harga Eceran Tertinggi (HET) resmi konsumen'
  },
  marketer: {
    id: 'marketer',
    name: 'Mitra Marketer',
    label: 'Marketer (15%)',
    discountPct: 15,
    minOrderNominal: 0,
    minOrderPcs: 1,
    badgeColor: '#0284c7',
    description: 'Bisa jualan tanpa modal, margin komisi 15%'
  },
  reseller: {
    id: 'reseller',
    name: 'Reseller Resmi',
    label: 'Reseller (20%)',
    discountPct: 20,
    minOrderNominal: 300000,
    minOrderPcs: 3,
    badgeColor: '#10b981',
    description: 'Margin 20%, minimal belanja awal Rp 300.000 / 3 pcs'
  },
  sub_agen: {
    id: 'sub_agen',
    name: 'Sub Agen SR12',
    label: 'Sub Agen (30%)',
    discountPct: 30,
    minOrderNominal: 1500000,
    minOrderPcs: 15,
    badgeColor: '#8b5cf6',
    description: 'Margin 30%, minimal order Rp 1.500.000 / 15 pcs'
  },
  agen: {
    id: 'agen',
    name: 'Agen Resmi SR12',
    label: 'Agen (40%)',
    discountPct: 40,
    minOrderNominal: 5000000,
    minOrderPcs: 50,
    badgeColor: '#f59e0b',
    description: 'Margin 40%, minimal order kartonan / Rp 5.000.000'
  },
  distributor: {
    id: 'distributor',
    name: 'Distributor Utama',
    label: 'Distributor (50%)',
    discountPct: 50,
    minOrderNominal: 15000000,
    minOrderPcs: 150,
    badgeColor: '#dc2626',
    description: 'Margin maksimal 50%, pemegang stok wilayah besar'
  }
};

// Helper SVG Generator for distinct realistic herbal cosmetics products
function makeProductIllustration(theme, icon, label, sub) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300">
    <defs>
      <linearGradient id="g_${theme}" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="${theme === 'green' ? '#064e3b' : theme === 'gold' ? '#78350f' : theme === 'blue' ? '#0c4a6e' : theme === 'purple' ? '#581c87' : theme === 'rose' ? '#831843' : '#14532d'}"/>
        <stop offset="100%" stop-color="${theme === 'green' ? '#047857' : theme === 'gold' ? '#d97706' : theme === 'blue' ? '#0284c7' : theme === 'purple' ? '#9333ea' : theme === 'rose' ? '#db2777' : '#16a34a'}"/>
      </linearGradient>
    </defs>
    <rect width="400" height="300" fill="url(#g_${theme})"/>
    <circle cx="200" cy="120" r="75" fill="rgba(255,255,255,0.12)" stroke="rgba(255,255,255,0.25)" stroke-width="2"/>
    <text x="200" y="140" font-size="64" text-anchor="middle" dominant-baseline="middle">${icon}</text>
    <rect x="50" y="210" width="300" height="60" rx="10" fill="rgba(0,0,0,0.3)" stroke="rgba(255,255,255,0.2)"/>
    <text x="200" y="235" font-family="'Plus Jakarta Sans', Arial, sans-serif" font-weight="bold" font-size="16" fill="#ffffff" text-anchor="middle">${label}</text>
    <text x="200" y="255" font-family="'Plus Jakarta Sans', Arial, sans-serif" font-size="12" fill="#fde68a" text-anchor="middle">${sub}</text>
  </svg>`;
  return 'data:image/svg+xml;utf8,' + encodeURIComponent(svg);
}

// Database Master Produk Resmi SR12 (Dengan visual khusus yang berbeda)
const DEFAULT_SR12_PRODUCTS = [
  {
    id: "sr12-lightening-body-lotion",
    name: "Lightening Body Lotion Tube",
    category: "Body Care",
    sku: "SR12-LBL-TUBE",
    bpom: "NA18190122375",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('rose', '🧴', 'LIGHTENING BODY LOTION', 'Mencerahkan & Melembabkan Kulit'),
    het: 80500,
    price: 80500,
    weightGram: 100,
    netto: "100 ml",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 1420,
    summary: "Body lotion dengan kandungan ekstrak alami untuk mencerahkan dan merawat kelembapan kulit tubuh sepanjang hari."
  },
  {
    id: "sr12-massage-oil-bulus",
    name: "Massage Oil Bulus",
    category: "Body Care",
    sku: "SR12-MOB-100",
    bpom: "NA18170101720",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('gold', '🐢', 'MASSAGE OIL BULUS', 'Minyak Bulus Murni Multi Khasiat'),
    het: 130000,
    price: 130000,
    weightGram: 100,
    netto: "100 ml",
    stock: 50,
    isBestseller: true,
    rating: 5,
    soldCount: 2350,
    summary: "Minyak bulus murni berkualitas tinggi untuk merawat kekencangan kulit, menyamarkan stretch mark, dan melembabkan."
  },
  {
    id: "sr12-miss-manja-spray",
    name: "Miss Manja Spray",
    category: "Body Care",
    sku: "SR12-MMS-60",
    bpom: "NA18221600078",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('purple', '🌸', 'MISS MANJA SPRAY', 'Perawatan Area Kewanitaan Praktis'),
    het: 57000,
    price: 57000,
    weightGram: 60,
    netto: "60 ml",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 1890,
    summary: "Semprotan higienis khusus area kewanitaan dengan ekstrak manjakani untuk kesegaran dan kenyamanan seharian."
  },
  {
    id: "sr12-miss-manja-wash",
    name: "Miss Manja Wash",
    category: "Body Care",
    sku: "SR12-MMW-100",
    bpom: "NA18221600077",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('purple', '🫧', 'MISS MANJA WASH', 'Sabun Pembersih Kewanitaan Lembut'),
    het: 57000,
    price: 57000,
    weightGram: 100,
    netto: "100 ml",
    stock: 50,
    isBestseller: false,
    rating: 4.8,
    soldCount: 940,
    summary: "Pembersih kewanitaan dengan formula pH seimbang untuk menjaga kebersihan dan mencegah bakteri penyebab bau."
  },
  {
    id: "sr12-paket-miss-manja",
    name: "Paket Miss Manja Wash-Spray",
    category: "Body Care",
    sku: "SR12-PKT-MM",
    bpom: "NA18221600077",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('purple', '🎁', 'PAKET MISS MANJA', 'Kombo Wash & Spray Hemat'),
    het: 100000,
    price: 100000,
    weightGram: 160,
    netto: "Paket Kombo",
    stock: 50,
    isBestseller: true,
    rating: 5,
    soldCount: 1650,
    summary: "Paket hemat kombo Miss Manja Wash dan Miss Manja Spray untuk perawatan kewanitaan maksimal."
  },
  {
    id: "sr12-dna-salmon-day-cream",
    name: "DNA Salmon Day Cream",
    category: "Face Care",
    sku: "SR12-DNA-DAY",
    bpom: "NA18220101826",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('rose', '☀️', 'DNA SALMON DAY CREAM', 'Krim Pagi Anti-Aging & UV Protection'),
    het: 112500,
    price: 112500,
    weightGram: 15,
    netto: "12.5 gr",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 2100,
    summary: "Krim siang premium dengan DNA Salmon murni untuk meremajakan kulit, menyamarkan garis halus, dan melindungi dari sinar UV."
  },
  {
    id: "sr12-dna-salmon-night-cream",
    name: "DNA Salmon Night Cream",
    category: "Face Care",
    sku: "SR12-DNA-NIGHT",
    bpom: "NA18220101825",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('blue', '🌙', 'DNA SALMON NIGHT CREAM', 'Krim Malam Regenerasi Sel Kulit'),
    het: 112500,
    price: 112500,
    weightGram: 15,
    netto: "12.5 gr",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 2050,
    summary: "Krim malam kaya nutrisi DNA Salmon untuk meregenerasi sel kulit saat tidur sehingga tampak glowing di pagi hari."
  },
  {
    id: "sr12-dna-salmon-soap-bar",
    name: "DNA Salmon Soap Bar",
    category: "Face Care",
    sku: "SR12-DNA-SOAP",
    bpom: "NA18220500135",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('gold', '🧼', 'DNA SALMON SOAP BAR', 'Sabun Batang Cuci Muka Glowing'),
    het: 44000,
    price: 44000,
    weightGram: 60,
    netto: "60 gr",
    stock: 50,
    isBestseller: false,
    rating: 4.8,
    soldCount: 1180,
    summary: "Sabun pembersih wajah berbentuk bar dengan ekstrak DNA Salmon untuk membersihkan pori tanpa membuat kulit kering."
  },
  {
    id: "sr12-paket-dna-salmon",
    name: "Paket DNA Salmon",
    category: "Face Care",
    sku: "SR12-PKT-DNA",
    bpom: "NA18220101826",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('rose', '✨', 'PAKET LENGKAP DNA SALMON', 'Day + Night Cream + Soap Bar'),
    het: 253000,
    price: 253000,
    weightGram: 90,
    netto: "Paket Lengkap",
    stock: 50,
    isBestseller: true,
    rating: 5,
    soldCount: 1720,
    summary: "Rangkaian lengkap DNA Salmon (Day Cream, Night Cream, dan Soap Bar) untuk hasil kulit cerah kenyal awet muda."
  },
  {
    id: "sr12-toner-bha",
    name: "Toner BHA",
    category: "Face Care",
    sku: "SR12-TONER-BHA",
    bpom: "NA18201203450",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('green', '💧', 'TONER BHA SR12', 'Eksfoliasi Lembut & Bersihkan Komedo'),
    het: 88000,
    price: 88000,
    weightGram: 100,
    netto: "100 ml",
    stock: 50,
    isBestseller: false,
    rating: 4.8,
    soldCount: 880,
    summary: "Toner wajah dengan Salicylic Acid (BHA) untuk membersihkan pori-pori tersumbat, mengatasi komedo, dan mencegah jerawat."
  },
  {
    id: "sr12-facial-foam-glutation-collagen",
    name: "Facial Foam Glutation With Collagen",
    category: "Face Care",
    sku: "SR12-FF-GLUT",
    bpom: "NA18211202390",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('rose', '🫧', 'FACIAL FOAM GLUTATION', 'Glutathione + Collagen Pembersih Wajah'),
    het: 92000,
    price: 92000,
    weightGram: 100,
    netto: "100 ml",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 1320,
    summary: "Busa pembersih wajah melimpah mengandung Glutathione dan Kolagen untuk mencerahkan dan menjaga elastisitas kulit."
  },
  {
    id: "sr12-facial-wash-coffee-100",
    name: "Facial Wash Coffee 100 ml",
    category: "Face Care",
    sku: "SR12-FW-COFFEE",
    bpom: "NA18201202334",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('gold', '☕', 'FACIAL WASH COFFEE', 'Kopi Alami Samarkan Bekas Jerawat'),
    het: 77500,
    price: 77500,
    weightGram: 100,
    netto: "100 ml",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 1540,
    summary: "Pembersih wajah dengan ekstrak biji kopi pilihan untuk mengangkat sel kulit mati dan menyamarkan noda flek hitam."
  },
  {
    id: "sr12-facial-wash-green-tea-100",
    name: "Facial Wash Green Tea 100 ml (NP)",
    category: "Face Care",
    sku: "SR12-FW-GREENTEA",
    bpom: "NA18201202335",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('green', '🍵', 'FACIAL WASH GREEN TEA', 'Teh Hijau Antioksidan Kulit Berminyak'),
    het: 72500,
    price: 72500,
    weightGram: 100,
    netto: "100 ml",
    stock: 50,
    isBestseller: false,
    rating: 4.8,
    soldCount: 920,
    summary: "Pembersih wajah dengan ekstrak teh hijau untuk mengontrol minyak berlebih dan meredakan jerawat meradang."
  },
  {
    id: "sr12-facial-wash-honey-100",
    name: "Facial Wash Honey 100 ml",
    category: "Face Care",
    sku: "SR12-FW-HONEY",
    bpom: "NA18201202336",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('gold', '🍯', 'FACIAL WASH HONEY', 'Madu Alami untuk Kulit Normal & Kering'),
    het: 75500,
    price: 75500,
    weightGram: 100,
    netto: "100 ml",
    stock: 50,
    isBestseller: false,
    rating: 4.8,
    soldCount: 860,
    summary: "Sabun wajah ekstrak madu alami yang melembutkan, menutrisi, dan menjaga kelembapan kulit normal hingga kering."
  },
  {
    id: "sr12-habbatussauda",
    name: "Habbatussauda",
    category: "Herbal",
    sku: "SR12-HAB-120",
    bpom: "TR183318531",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('green', '🌿', 'HABBATUSSAUDA SR12', 'Minyak Jintan Hitam Kapsul Imunitas'),
    het: 140000,
    price: 140000,
    weightGram: 150,
    netto: "120 Kapsul",
    stock: 50,
    isBestseller: true,
    rating: 5,
    soldCount: 2150,
    summary: "Minyak Habbatussauda murni berkualitas tinggi dalam kapsul untuk meningkatkan daya tahan tubuh dan stamina."
  },
  {
    id: "sr12-lemonkuh-250",
    name: "Lemonkuh SR12 250 ml",
    category: "Herbal",
    sku: "SR12-LMN-250",
    bpom: "MD265728013050",
    halal: "MUI-00120108351120",
    image: makeProductIllustration('gold', '🍋', 'LEMONKUH SR12 250 ML', 'Sari Lemon Murni 100% Tanpa Pengawet'),
    het: 81000,
    price: 81000,
    weightGram: 300,
    netto: "250 ml",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 1980,
    summary: "100% perasan sari lemon murni kaya vitamin C untuk detoksifikasi, menjaga imunitas, dan melangsingkan tubuh."
  },
  {
    id: "sr12-lemonkuh-500",
    name: "Lemonkuh SR12 500 ml",
    category: "Herbal",
    sku: "SR12-LMN-500",
    bpom: "MD265728013050",
    halal: "MUI-00120108351120",
    image: makeProductIllustration('gold', '🍋', 'LEMONKUH SR12 500 ML', 'Sari Lemon Murni Kemasan Keluarga Hemat'),
    het: 114000,
    price: 114000,
    weightGram: 550,
    netto: "500 ml",
    stock: 50,
    isBestseller: true,
    rating: 5,
    soldCount: 1640,
    summary: "Sari lemon murni kemasan besar 500 ml lebih hemat untuk konsumsi kesehatan seluruh keluarga."
  },
  {
    id: "sr12-maxi-propolis",
    name: "Maxi Propolis",
    category: "Herbal",
    sku: "SR12-MAX-PROP",
    bpom: "TR213642221",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('gold', '🐝', 'MAXI PROPOLIS SR12', 'Ekstrak Propolis Alami Nanoteknologi'),
    het: 138000,
    price: 138000,
    weightGram: 50,
    netto: "10 ml",
    stock: 50,
    isBestseller: true,
    rating: 5,
    soldCount: 2400,
    summary: "Ekstrak propolis lebah dengan teknologi nano cepat serap untuk antibiotik alami, mengobati radang, dan mempercepat penyembuhan."
  },
  {
    id: "sr12-sari-kurma",
    name: "Sari Kurma SR12",
    category: "Herbal",
    sku: "SR12-SK-350",
    bpom: "MD865728017050",
    halal: "MUI-00120108351120",
    image: makeProductIllustration('gold', '🌴', 'SARI KURMA SR12', 'Sari Buah Kurma Asli Penambah Trombosit'),
    het: 79000,
    price: 79000,
    weightGram: 400,
    netto: "350 gr",
    stock: 50,
    isBestseller: false,
    rating: 4.8,
    soldCount: 1120,
    summary: "Sari kurma murni kualitas istimewa untuk menaikkan trombosit, penambah energi alami, dan nutrisi ibu hamil/menyusui."
  },
  {
    id: "sr12-herbal-manjakani",
    name: "SR12 Herbal Manjakani",
    category: "Herbal",
    sku: "SR12-MJK-BUTIR",
    bpom: "TR183311871",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('purple', '🌸', 'MANJAKANI SR12', 'Ekstrak Buah Manjakani Persia Legendaris'),
    het: 85000,
    price: 85000,
    weightGram: 80,
    netto: "60 Butir",
    stock: 50,
    isBestseller: true,
    rating: 5,
    soldCount: 3800,
    summary: "Formulasi herbal buah manjakani Persia asli untuk kesehatan organ intim wanita, mengatasi keputihan, dan merapatkan."
  },
  {
    id: "sr12-stevia-5ml",
    name: "Stevia SR12 (5ml)",
    category: "Herbal",
    sku: "SR12-STV-5",
    bpom: "MD878028003050",
    halal: "MUI-00120108351120",
    image: makeProductIllustration('green', '🍃', 'STEVIA SR12 5ML', 'Pemanis Alami 0 Kalori Pengganti Gula'),
    het: 45000,
    price: 45000,
    weightGram: 30,
    netto: "5 ml",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 1750,
    summary: "Tetes pemanis alami daun stevia murni 0 kalori, aman untuk penderita diabetes dan program diet sehat."
  },
  {
    id: "sr12-vco-oil-60ml",
    name: "V-CO Oil SR12 60ml",
    category: "Herbal",
    sku: "SR12-VCO-60",
    bpom: "TR173606151",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('blue', '🥥', 'VCO SR12 60 ML', 'Virgin Coconut Oil Cold Pressed Murni'),
    het: 48000,
    price: 48000,
    weightGram: 80,
    netto: "60 ml",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 2200,
    summary: "Minyak kelapa murni (Virgin Coconut Oil) diproses dingin (cold pressed) tanpa pemanasan untuk kesehatan dan kecantikan."
  },
  {
    id: "sr12-vco-oil-100ml",
    name: "V-CO Oil SR12 100ml",
    category: "Herbal",
    sku: "SR12-VCO-100",
    bpom: "TR173606151",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('blue', '🥥', 'VCO SR12 100 ML', 'Virgin Coconut Oil Kemasan Sedang'),
    het: 62000,
    price: 62000,
    weightGram: 130,
    netto: "100 ml",
    stock: 50,
    isBestseller: true,
    rating: 5,
    soldCount: 2890,
    summary: "Minyak kelapa murni serbaguna untuk diminum menjaga imunitas atau dioleskan pada kulit dan rambut."
  },
  {
    id: "sr12-vco-oil-250ml",
    name: "V-CO Oil SR12 250ml",
    category: "Herbal",
    sku: "SR12-VCO-250",
    bpom: "TR173606151",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('blue', '🥥', 'VCO SR12 250 ML', 'Virgin Coconut Oil Kemasan Jumbo Hemat'),
    het: 113500,
    price: 113500,
    weightGram: 300,
    netto: "250 ml",
    stock: 50,
    isBestseller: true,
    rating: 5,
    soldCount: 1980,
    summary: "Kemasan besar 250 ml lebih ekonomis untuk konsumsi rutin keluarga dan terapi kesehatan alami."
  },
  {
    id: "sr12-vco-oil-kapsul",
    name: "V-CO Oil SR12 Kapsul",
    category: "Herbal",
    sku: "SR12-VCO-KAP",
    bpom: "TR173304931",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('blue', '💊', 'VCO KAPSUL SR12', 'Virgin Coconut Oil Kapsul Praktis'),
    het: 68000,
    price: 68000,
    weightGram: 100,
    netto: "100 Kapsul",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 2310,
    summary: "Minyak kelapa murni dalam bentuk kapsul praktis ditelan tanpa rasa enek untuk daya tahan tubuh dan diet sehat."
  },
  {
    id: "sr12-daily-cover-beige",
    name: "Daily Cover Beige",
    category: "Kosmetik",
    sku: "SR12-DC-BEIGE",
    bpom: "NA18201202035",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('gold', '🪞', 'DAILY COVER BEIGE', 'Bedak Padat Tahan Lama Shade Beige'),
    het: 110000,
    price: 110000,
    weightGram: 50,
    netto: "14 gr",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 1450,
    summary: "Compact powder bedak padat shade Beige yang menyamarkan noda hitam dan pori-pori dengan hasil matte tahan lama."
  },
  {
    id: "sr12-daily-cover-natural",
    name: "Daily Cover Natural",
    category: "Kosmetik",
    sku: "SR12-DC-NATURAL",
    bpom: "NA18201202036",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('gold', '🪞', 'DAILY COVER NATURAL', 'Bedak Padat Shade Natural Menyesuaikan Kulit'),
    het: 110000,
    price: 110000,
    weightGram: 50,
    netto: "14 gr",
    stock: 50,
    isBestseller: true,
    rating: 5,
    soldCount: 2100,
    summary: "Bedak padat shade Natural cocok untuk warna kulit wanita Indonesia dengan coverage sempurna dan halus di wajah."
  },
  {
    id: "sr12-daily-cover-sheerpink",
    name: "Daily Cover Sheerpink",
    category: "Kosmetik",
    sku: "SR12-DC-SHEERPINK",
    bpom: "NA18201202037",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('rose', '🪞', 'DAILY COVER SHEERPINK', 'Bedak Padat Rona Cerah Merona'),
    het: 110000,
    price: 110000,
    weightGram: 50,
    netto: "14 gr",
    stock: 50,
    isBestseller: false,
    rating: 4.8,
    soldCount: 890,
    summary: "Bedak padat shade Sheerpink memberikan rona wajah segar kemerahan cerah alami sepanjang hari."
  },
  {
    id: "sr12-lip-care-cherry",
    name: "Lip Care Cherry",
    category: "Kosmetik",
    sku: "SR12-LC-CHERRY",
    bpom: "NA18191305977",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('rose', '🍒', 'LIP CARE CHERRY', 'Pelembab Bibir Beraroma Cherry Merah Segar'),
    het: 37000,
    price: 37000,
    weightGram: 20,
    netto: "5 gr",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 3100,
    summary: "Pelembab bibir beraroma ceri segar yang merawat bibir kering pecah-pecah dan memberikan semburat warna merah alami."
  },
  {
    id: "sr12-lip-care-natural",
    name: "Lip Care Natural SR12",
    category: "Kosmetik",
    sku: "SR12-LC-NATURAL",
    bpom: "NA18191305978",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('rose', '👄', 'LIP CARE NATURAL', 'Pelembab Bibir Alami Bening Tanpa Warna'),
    het: 36500,
    price: 36500,
    weightGram: 20,
    netto: "5 gr",
    stock: 50,
    isBestseller: true,
    rating: 4.8,
    soldCount: 2800,
    summary: "Pelembab bibir alami tanpa pewarna dengan VCO dan petroleum jelly murni untuk bibir lembab sehat natural."
  },
  {
    id: "sr12-lip-cream-matte-cherish-me",
    name: "Lip Cream Matte Cherish Me",
    category: "Kosmetik",
    sku: "SR12-LCM-CHERISH",
    bpom: "NA18191306351",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('rose', '💄', 'LIP CREAM CHERISH ME', 'Lip Cream Matte Transferproof Cherish Me'),
    het: 65000,
    price: 65000,
    weightGram: 25,
    netto: "4 gr",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 1650,
    summary: "Lip cream matte warna Cherish Me bertekstur lembut ringan di bibir, tahan lama tanpa membuat bibir kering."
  },
  {
    id: "sr12-lip-cream-matte-honey-berry",
    name: "Lip Cream Matte Honey Berry",
    category: "Kosmetik",
    sku: "SR12-LCM-HONEY",
    bpom: "NA18191306352",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('rose', '💄', 'LIP CREAM HONEY BERRY', 'Warna Berry Hangat Memikat'),
    het: 65000,
    price: 65000,
    weightGram: 25,
    netto: "4 gr",
    stock: 50,
    isBestseller: false,
    rating: 4.8,
    soldCount: 940,
    summary: "Lip cream matte dengan shade Honey Berry yang elegan untuk tampilan kasual maupun pesta."
  },
  {
    id: "sr12-lip-cream-matte-nude-berry",
    name: "Lip Cream Matte Nude Berry",
    category: "Kosmetik",
    sku: "SR12-LCM-NUDE",
    bpom: "NA18191306353",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('rose', '💄', 'LIP CREAM NUDE BERRY', 'Shade Nude Natural Sehari-hari'),
    het: 65000,
    price: 65000,
    weightGram: 25,
    netto: "4 gr",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 1820,
    summary: "Lip cream matte shade Nude Berry favorit wanita untuk riasan bibir natural sehari-hari."
  },
  {
    id: "sr12-lip-cream-matte-sweet-pink",
    name: "Lip Cream Matte Sweet Pink",
    category: "Kosmetik",
    sku: "SR12-LCM-PINK",
    bpom: "NA18191306354",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('rose', '💄', 'LIP CREAM SWEET PINK', 'Warna Pink Feminin & Manis'),
    het: 65000,
    price: 65000,
    weightGram: 25,
    netto: "4 gr",
    stock: 50,
    isBestseller: false,
    rating: 4.8,
    soldCount: 880,
    summary: "Lip cream matte shade Sweet Pink memberikan sentuhan feminin yang ceria dan segar."
  },
  {
    id: "sr12-lip-cream-matte-sr01",
    name: "Lip Cream Matte SR01",
    category: "Kosmetik",
    sku: "SR12-LCM-SR01",
    bpom: "NA18191306350",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('rose', '💄', 'LIP CREAM SR01', 'Signature Shade Merah Klasik'),
    het: 65000,
    price: 65000,
    weightGram: 25,
    netto: "4 gr",
    stock: 50,
    isBestseller: false,
    rating: 4.8,
    soldCount: 760,
    summary: "Lip cream matte shade SR01 dengan warna merah klasik yang tegas dan mempesona."
  },
  {
    id: "sr12-lip-mousse-cream",
    name: "Lip Mousse Cream",
    category: "Kosmetik",
    sku: "SR12-LMC-ORI",
    bpom: "NA18201301980",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('rose', '💋', 'LIP MOUSSE CREAM', 'Tekstur Velvet Mousse Lembut Nyaman'),
    het: 66000,
    price: 66000,
    weightGram: 25,
    netto: "4 gr",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 1350,
    summary: "Pewarna bibir bertekstur mousse selembut beludru, tidak lengket dan memberikan efek bibir halus bervolume."
  },
  {
    id: "sr12-lip-mousse-rose-pink",
    name: "Lip Mousse Rose Pink",
    category: "Kosmetik",
    sku: "SR12-LMC-ROSE",
    bpom: "NA18201301981",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('rose', '💋', 'LIP MOUSSE ROSE PINK', 'Shade Rose Pink Segar Menawan'),
    het: 68000,
    price: 68000,
    weightGram: 25,
    netto: "4 gr",
    stock: 50,
    isBestseller: false,
    rating: 4.8,
    soldCount: 890,
    summary: "Lip mousse dengan rona mawar merah muda lembut yang mempercantik tampilan senyum Anda."
  },
  {
    id: "sr12-lip-mousse-sweet-brown",
    name: "Lip Mousse Sweet Brown",
    category: "Kosmetik",
    sku: "SR12-LMC-BROWN",
    bpom: "NA18201301982",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('gold', '💋', 'LIP MOUSSE SWEET BROWN', 'Shade Cokelat Manis Tren Kekinian'),
    het: 67000,
    price: 67000,
    weightGram: 25,
    netto: "4 gr",
    stock: 50,
    isBestseller: false,
    rating: 4.8,
    soldCount: 910,
    summary: "Lip mousse bernuansa cokelat manis elegan yang cocok untuk tema makeup hangat / warm tone."
  },
  {
    id: "sr12-matte-cover-natural-powder",
    name: "Matte Cover Natural Loose Powder",
    category: "Kosmetik",
    sku: "SR12-LP-NATURAL",
    bpom: "NA18200400030",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('gold', '✨', 'MATTE COVER LOOSE POWDER', 'Bedak Tabur Pengontrol Minyak Wajah'),
    het: 92000,
    price: 92000,
    weightGram: 50,
    netto: "15 gr",
    stock: 50,
    isBestseller: false,
    rating: 4.8,
    soldCount: 1100,
    summary: "Bedak tabur partikel halus untuk mengunci makeup, menyerap sebum berlebih, dan memberikan efek soft blur pada wajah."
  },
  {
    id: "sr12-perfect-cover-bb-cream-beige",
    name: "Perfect Cover BB Cream Natural Beige",
    category: "Kosmetik",
    sku: "SR12-BB-BEIGE",
    bpom: "NA18200300180",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('gold', '🧴', 'PERFECT COVER BB CREAM', 'Alas Bedak Ringan Natural Beige'),
    het: 90000,
    price: 90000,
    weightGram: 60,
    netto: "30 ml",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 1400,
    summary: "BB Cream ringan dengan coverage prima untuk menyamarkan ketidaksempurnaan wajah tanpa terasa tebal atau dempul."
  },
  {
    id: "sr12-perfect-cushion-ivory",
    name: "Perfect Cushion Ivory",
    category: "Kosmetik",
    sku: "SR12-CUSH-IVORY",
    bpom: "NA18210300450",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('rose', '✨', 'PERFECT CUSHION IVORY', 'Cushion Flawless untuk Kulit Terang'),
    het: 195000,
    price: 195000,
    weightGram: 60,
    netto: "15 gr",
    stock: 50,
    isBestseller: true,
    rating: 5,
    soldCount: 1780,
    summary: "Cushion berformula mewah shade Ivory untuk kulit cerah dengan hasil akhir glowing natural tahan seharian."
  },
  {
    id: "sr12-perfect-cushion-natural",
    name: "Perfect Cushion Natural",
    category: "Kosmetik",
    sku: "SR12-CUSH-NATURAL",
    bpom: "NA18210300451",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('gold', '✨', 'PERFECT CUSHION NATURAL', 'Cushion Flawless Shade Natural'),
    het: 203500,
    price: 203500,
    weightGram: 60,
    netto: "15 gr",
    stock: 50,
    isBestseller: true,
    rating: 5,
    soldCount: 2250,
    summary: "Cushion shade Natural yang menyatu sempurna dengan warna kulit, menyamarkan noda hitam dan pori dengan perlindungan UV."
  },
  {
    id: "sr12-pasta-gigi-siwak-sirih-100",
    name: "Pasta Gigi Siwak & Sirih 100gr",
    category: "Personal Care",
    sku: "SR12-PG-100",
    bpom: "NA18211400015",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('green', '🪥', 'PASTA GIGI SIWAK SIRIH 100G', 'Herbal Alami Perawatan Gigi & Gusi'),
    het: 67000,
    price: 67000,
    weightGram: 120,
    netto: "100 gr",
    stock: 50,
    isBestseller: true,
    rating: 4.9,
    soldCount: 2600,
    summary: "Pasta gigi herbal ekstrak kayu siwak dan daun sirih untuk mencegah gigi berlubang, menyegarkan nafas, dan menjaga kesehatan gusi."
  },
  {
    id: "sr12-pasta-gigi-siwak-sirih-170",
    name: "Pasta Gigi Siwak & Sirih 170gr",
    category: "Personal Care",
    sku: "SR12-PG-170",
    bpom: "NA18211400015",
    halal: "MUI-00150084520917",
    image: makeProductIllustration('green', '🪥', 'PASTA GIGI SIWAK SIRIH 170G', 'Pasta Gigi Herbal Kemasan Hemat Keluarga'),
    het: 82000,
    price: 82000,
    weightGram: 200,
    netto: "170 gr",
    stock: 50,
    isBestseller: true,
    rating: 5,
    soldCount: 2900,
    summary: "Pasta gigi siwak & sirih kemasan keluarga 170 gr lebih hemat untuk perlindungan mulut dan gigi seluruh anggota keluarga."
  }
];

// Whitelist Validasi SR12
const SR12_OFFICIAL_WHITELIST = {
  brandName: 'SR12 Herbal Skin Care',
  allowedPrefixes: ['SR12-', 'SR-'],
  validBPOMPrefixes: ['NA18', 'TR18', 'TR16', 'TR17', 'TR19', 'NA19', 'NA20', 'NA21', 'NA22', 'NA23', 'NA24', 'NA25', 'MD80'],
  knownSKUs: [
    'SR12-DEO-60', 'SR12-DEO-PREM', 'SR12-LIP-01', 'SR12-MJK-01', 'SR12-SLM-01',
    'SR12-BLS-SOAP', 'SR12-BLS-OIL', 'SR12-VCO-100', 'SR12-VCO-250', 'SR12-SUN-30',
    'SR12-COF-MASK', 'SR12-KRASNY-DAY', 'SR12-KRASNY-NIGHT', 'SR12-GOMILK-ORI',
    'SR12-SHAMPOO-APPLE', 'SR12-TONER-CHAMOMILE', 'SR12-ACNE-TOTOL', 'SR12-SERUM-GOLD',
    'SR12-RICE-SOAP'
  ]
};

// Database Reward (Program Resmi Nasional vs Promo Khusus Toko)
const DEFAULT_SR12_REWARDS = [
  {
    id: 'rew-resmi-1',
    scope: 'resmi',
    title: 'Logam Mulia Emas Antam 0.5 Gram (Resmi)',
    requiredPoints: 500,
    category: 'Emas Murni',
    description: 'Program reward resmi PT. SR12 Herbal Perkasa untuk akumulasi poin repeat order mitra.',
    badge: 'Program Resmi SR12 Pusat'
  },
  {
    id: 'rew-resmi-2',
    scope: 'resmi',
    title: 'Logam Mulia Emas Antam 2.0 Gram (Resmi)',
    requiredPoints: 1800,
    category: 'Emas Murni',
    description: 'Reward tahunan resmi untuk pencapaian omzet kemitraan Agen & Distributor.',
    badge: 'Program Resmi SR12 Pusat'
  },
  {
    id: 'rew-resmi-3',
    scope: 'resmi',
    title: 'Paket Ibadah Umrah SR12 Eksekutif 9 Hari',
    requiredPoints: 25000,
    category: 'Grand Prize',
    description: 'Grand Prize Tahunan dari Manajemen Pusat SR12 untuk mitra berprestasi.',
    badge: 'Grand Prize Nasional'
  },
  {
    id: 'rew-toko-1',
    scope: 'toko',
    title: 'Bonus 2 Pcs Lip Care (Promo Gajian Toko)',
    requiredPoints: 50,
    category: 'Promo Toko',
    description: 'Khusus pembelanjaan minggu ini: bonus langsung 2 pcs Lip Care dari Distributor toko ini.',
    badge: 'Promo Khusus Toko Kami'
  },
  {
    id: 'rew-toko-2',
    scope: 'toko',
    title: 'Cashback Belanja Rp 150.000',
    requiredPoints: 150,
    category: 'Cashback Toko',
    description: 'Insentif saldo pembelanjaan tambahan khusus tim reseller internal kami.',
    badge: 'Insentif Internal'
  }
];

// Marketing Kit & Bahan Promosi Siap Share
const DEFAULT_MARKETING_KITS = [
  {
    id: 'mk-1',
    productName: 'SR12 Deodorant Spray Herbal',
    headline: 'Bebas Bau Badan 24 Jam Nonstop!',
    caption: `Bau badan bikin minder pas kumpul sama teman atau keluarga? 🥺\n\nNih rahasia ketiak tetap wangi segar seharian tanpa noda kuning di baju: SR12 Deodorant Spray Herbal! 🍃\n\n✨ 100% bahan alami tawas pilihan\n✨ Mencegah bau badan 24 jam nonstop\n✨ Bantu mencerahkan ketiak\n✨ Sudah BPOM & Halal MUI!\n\nHarga cuma Rp 40.000 tapi awet dipakai 2-3 bulan! Mau order sekarang sebelum kehabisan? Langsung WA ya: [No HP Kamu] 📲`,
    tags: ['#SR12Deodorant', '#SR12HerbalSkinCare', '#BebasBauBadan', '#HalalBPOM']
  },
  {
    id: 'mk-2',
    productName: 'SR12 GoMilku Susu Kambing Etawa',
    headline: 'Asam Lambung & Maag Sembuh Alami',
    caption: `Sering kembung, begah, atau perih ulu hati karena asam lambung naik? 🥛\n\nIkhtiar sehat yuk dengan SR12 GoMilku! Susu kambing etawa premium yang diformulasikan khusus dengan Daun Kelor, Ikan Gabus, dan Madu murni.\n\n🌿 Menetralisir asam lambung & maag\n🌿 Memperkuat sendi dan tulang\n🌿 Rasanya gurih enak, sama sekali TIDAK AMIS/PRENGUS!\n🌿 Cocok untuk anak-anak hingga lansia\n\nYuk sediakan GoMilku untuk kesehatan keluarga tercinta. Chat admin sekarang yuk! 💕`,
    tags: ['#GoMilkuSR12', '#SusuKambingEtawa', '#SolusiMaag', '#HerbalKeluarga']
  },
  {
    id: 'mk-3',
    productName: 'SR12 Manjakani & Herbal Rahasia Wanita',
    headline: 'Solusi Tuntas Keputihan & Masalah Kewanitaan',
    caption: `Bunda sering merasa risih dengan masalah keputihan atau haid yang tidak teratur? 🌸\n\nAlhamdulillah ribuan wanita sudah membuktikan khasiat legendaris Manjakani SR12! Diproses secara higienis dari buah manjakani Persia kualitas nomor satu.\n\n✅ Tuntaskan keputihan & bau tidak sedap\n✅ Merapatkan organ kewanitaan\n✅ Terdaftar resmi BPOM TR183311871\n\nKonsultasi gratis & pemesanan langsung chat ke WhatsApp ya sist! 💌`,
    tags: ['#ManjakaniSR12', '#HerbalKewanitaan', '#SR12Herbal', '#RahasiaWanita']
  },
  {
    id: 'mk-4',
    productName: 'Paket Diet Sehat (Salimah Slim + VCO)',
    headline: 'Turun Berat Badan Tanpa Mules Tersiksa',
    caption: `Mau turun 2-5 kg tanpa tersiksa lapar dan lemas? 🍋\n\nDuet maut Salimah Slim + VCO SR12 herbal siap bantu detoks lemak jahat dan lancarkan metabolisme tubuh secara alami!\n\n🌿 Kunyit & Jati Belanda meluruhkan lemak\n🌿 VCO menjaga energi & rasa kenyang\n🌿 Bebas bahan kimia berbahaya\n\nYuk mulai hidup sehat dan langsing ideal! Hubungi admin di [No HP Kamu] 📲`,
    tags: ['#SalimahSlimSR12', '#DietHerbalAlami', '#VCOSR12', '#LangsingSehat']
  }
];

// Ekspedisi & Metode Pengambilan / Pengiriman
const SR12_SHIPPING_PROVIDERS = [
  { id: 'jne', name: 'JNE Express (Reguler)', costPerKg: 12000, estDays: '2-3 hari', minKg: 1, type: 'courier' },
  { id: 'jnt', name: 'J&T Express (Kilat)', costPerKg: 14000, estDays: '1-2 hari', minKg: 1, type: 'courier' },
  { id: 'sicepat', name: 'SiCepat Halu / Reguler', costPerKg: 11000, estDays: '2-3 hari', minKg: 1, type: 'courier' },
  { id: 'cod', name: '💵 COD (Bayar Tunai di Tempat saat Sampai)', costPerKg: 15000, estDays: '1-3 hari', minKg: 1, type: 'cod' },
  { id: 'pickup', name: '🏪 Ambil Sendiri di Toko/Gudang (Bebas Ongkir - Rp 0)', costPerKg: 0, estDays: 'Bisa langsung diambil', minKg: 1, type: 'pickup' },
  { id: 'instant', name: '⚡ Kurir Instan / Same Day (GoSend / GrabExpress)', costPerKg: 20000, estDays: '1-3 jam', minKg: 1, type: 'instant' },
  { id: 'kargo', name: '🚛 J&T Cargo / Indah Kargo (Grosir Min. 10 kg)', costPerKg: 3500, estDays: '3-5 hari', minKg: 10, type: 'cargo' }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { DEFAULT_SR12_PRODUCTS, SR12_TIERS, SR12_SHIPPING_PROVIDERS };
}
